// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrainAlert.Api.Data;

#nullable disable

namespace TrainAlert.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261001105533_AddCancellationToNotifications")]
    partial class AddCancellationToNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrainAlert.Api.Models.AlertConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationStationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DestinationStationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginStationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginStationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("TrainAlert.Api.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlertId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("CurrentCancelled")
                        .HasColumnType("boolean");

                    b.Property<int?>("CurrentDelayMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("CurrentDisruptionReason")
                        .HasColumnType("text");

                    b.Property<bool?>("CurrentNotDeparted")
                        .HasColumnType("boolean");

                    b.Property<string>("CurrentPlatform")
                        .HasColumnType("text");

                    b.Property<bool?>("CurrentRunning")
                        .HasColumnType("boolean");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("PreviousCancelled")
                        .HasColumnType("boolean");

                    b.Property<int?>("PreviousDelayMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("PreviousDisruptionReason")
                        .HasColumnType("text");

                    b.Property<bool?>("PreviousNotDeparted")
                        .HasColumnType("boolean");

                    b.Property<string>("PreviousPlatform")
                        .HasColumnType("text");

                    b.Property<bool?>("PreviousRunning")
                        .HasColumnType("boolean");

                    b.Property<string>("TrainNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlertId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("TrainAlert.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TrainAlert.Api.Models.AlertConfiguration", b =>
                {
                    b.HasOne("TrainAlert.Api.Models.User", "User")
                        .WithMany("Alerts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainAlert.Api.Models.Notification", b =>
                {
                    b.HasOne("TrainAlert.Api.Models.AlertConfiguration", "Alert")
                        .WithMany()
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainAlert.Api.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alert");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainAlert.Api.Models.User", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
